# 配置RabbitMQ的基本信息  ip 端口 username  password..
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zero
    password: zero
    virtual-host: /study
  output:
    ansi:
      enabled: always