spring:
  #  控制台彩色输出
  output:
    ansi:
      enabled: always
  #  配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: AngelBeats
  #  redis配置
  redis:
    host: 121.36.24.140
    password: aiya
  freemarker:
    cache: true

server:
  port: 8888
  #servlet:
  #context-path: /test

#配置日志
logging:
  level:
    com.yileaf: trace
    org.springframework: info

#配置mybatis plus
mybatis-plus:
  type-aliases-package: com.yileaf.model
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml