spring:
  output:
    ansi:
      enabled: always
  application:
    name: consumer-service #服务消费应用名称

#配置eureka注册服务地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #获取服务地址列表间隔时间，默认30秒


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #Hystrix的默认超时时长为1秒，修改为两秒
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 10 # 熔断触发最小请求次数，默认值是20