spring:
  #  控制台彩色输出
  output:
    ansi:
      enabled: always
    #  配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: AngelBeats

server:
  port: 9000

#配置mybatis plus
mybatis-plus:
  type-aliases-package: com.provider.pojo

# 配置日志级别
logging:
  level:
    com.provider: debug
